# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Swarmctl < Formula
  desc "A k8s service swarm"
  homepage "https://github.com/h0tbird/k-swarm"
  version "0.3.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/h0tbird/k-swarm/releases/download/v0.3.3/swarmctl_0.3.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3bf85910b1e926ae9d7ee15b328b558f05167e188ad59dc12fd2a4d21fbbbeef"

      def install
        bin.install "swarmctl"
      end
    end
    on_arm do
      url "https://github.com/h0tbird/k-swarm/releases/download/v0.3.3/swarmctl_0.3.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "12fd8b6b678b4cf685b2719aca9e59fa842318339a56a8e9195723ce3eb81e9a"

      def install
        bin.install "swarmctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/h0tbird/k-swarm/releases/download/v0.3.3/swarmctl_0.3.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "68282402812afcc01afcfd1fe23221eadf10779a3887e1c9cd816fe966465f1f"

        def install
          bin.install "swarmctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/h0tbird/k-swarm/releases/download/v0.3.3/swarmctl_0.3.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "cf53df554c58cd146ee1ffad55059d7bf39cfdd40a13fda938aa23b87a00cbcc"

        def install
          bin.install "swarmctl"
        end
      end
    end
  end

  test do
    system "#{bin}/swarmctl -v"
  end
end
